### ISSUE TITLE
WASD MENU

### ISSUE THREAD

**Issue by Fate9707** [Oz-Lin/cs2-rockthevote#1]
WASD MENU to avoid using nominate or map commands when voting?

**Comment by Oz-Lin** [comment]
Hi, just wondering which part of the plugin feature are you talking about.
Is it the WASD for `!nominate`? Or for `!votemap`? Or using WASD to choose a map during the end of map vote? 
I currently modify the plugins to suit the use cases in the zombie escape mod, haven't been dealing with WASD APIs yet

**Comment by Fate9707** [comment]
> Hi, just wondering which part of the plugin feature are you talking about. Is it the WASD for `!nominate`? Or for `!votemap`? Or using WASD to choose a map during the end of map vote? I currently modify the plugins to suit the use cases in the zombie escape mod, haven't been dealing with WASD APIs yet

all those where you have to write the commands to !1 -!8.
so nominate map when voting etc.

**Comment by Oz-Lin** [comment]
> all those where you have to write the commands to !1 -!8.
> so nominate map when voting etc.
> 

I will investigate the WASD APIs later. Can't guarantee if I can make it though.

Meanwhile if you have a numpad on your keyboard, you can do 
`bind kp_1 css_1`
`bind kp_2 css_2`
`bind kp_3 css_3`
Etc

**Comment by Letaryat** [comment]
Just wanted to add that using MenuManager by NickFox007 it would be easy to implement (https://github.com/NickFox007/MenuManagerCS2/releases). But it does need some other dependencies.

**Comment by chycken** [comment]
@Oz-Lin hey, if u will add wasd menu to this plugin which would be awesome, this is the best (can be opened while youre dead, there is back button, configurable buttons..): https://github.com/T3Marius/T3Menu-API
