### ISSUE TITLE
Timer not working

### ISSUE THREAD

**Issue by RafaelBetz** [Oz-Lin/cs2-rockthevote#6]
Hey, when triggering !rtv or waiting for the mapchange the Timer in the hud is not shown, see screenshot.

![730_5](https://github.com/user-attachments/assets/1bcc7ba4-113c-43b5-8a64-dc50bee2339a)

**Comment by Oz-Lin** [comment]
Looks like it's missing translation phrase files on the server.

If you are not using English or Chinese as a main language, make sure you update the language files on your own (they are marked as outdated).

**Comment by RafaelBetz** [comment]
> Looks like it's missing translation phrase files on the server.
> 
> If you are not using English or Chinese as a main language, make sure you update the language files on your own (they are marked as outdated).

I thought about this aswell, but as you can see it shows (!1 Extend Current Map) english language. Also in all lang files the emv.hud.hud-timer is maintained.

```
cs2server@admin:~/serverfiles/game/csgo/addons/counterstrikesharp/plugins/RockTheVote/lang$ grep -R emv.hud.hud-timer *
en.json:  "emv.hud.hud-timer": "Vote for the next map: {0}s",
fr.outdated.json:  "emv.hud.hud-timer": "Votez pour la prochaine carte : {0}s",
hu.outdated.json:  "emv.hud.hud-timer": "Szavazz a következő pályára: {0}mp",
lv.outdated.json:  "emv.hud.hud-timer": "Balso par nākošo karti: {0}s",
pl.outdated.json:  "emv.hud.hud-timer": "Głosuj na następną mapę: {0}s",
pt-BR.outdated.json:  "emv.hud.hud-timer": "Vote para o próximo mapa: {0}s",
ru.outdated.json:  "emv.hud.hud-timer": "Голосование за следующую карту: {0}s",
tr.outdated.json:  "emv.hud.hud-timer": "Sonraki haritaya oy verin: {0}",
ua.outdated.json:  "emv.hud.hud-timer": "Голосуйте за наступну карту: {0}с",
zh-Hans.json:  "emv.hud.hud-timer": "投票下一张地图: {0}s",
zh-Hant.json:	"emv.hud.hud-timer": "投票下一張地圖: {0}s",
```

**Comment by Oz-Lin** [comment]
The "Extend Current Map" in the hud menu is hardcoded, otherwise the vote is broken.
But it should display in your language in the chat menu part.

```
fr.outdated.json:  "emv.hud.hud-timer": "Votez pour la prochaine carte : {0}s",
hu.outdated.json:  "emv.hud.hud-timer": "Szavazz a következő pályára: {0}mp",
lv.outdated.json:  "emv.hud.hud-timer": "Balso par nākošo karti: {0}s",
pl.outdated.json:  "emv.hud.hud-timer": "Głosuj na następną mapę: {0}s",
pt-BR.outdated.json:  "emv.hud.hud-timer": "Vote para o próximo mapa: {0}s",
ru.outdated.json:  "emv.hud.hud-timer": "Голосование за следующую карту: {0}s",
tr.outdated.json:  "emv.hud.hud-timer": "Sonraki haritaya oy verin: {0}",
ua.outdated.json:  "emv.hud.hud-timer": "Голосуйте за наступну карту: {0}с",
```
If you are using one of these languages on your server, once you finished updating the language files on your own, remove the `outdated` in the file name
